### PR TITLE
depend on dep1 as an internal target

### PR DESCRIPTION
**Pull request by ittaiz**
and not from external repo
@AlexShemeshWix do you know if the below was generated by Gazelle? If so it looks weird but maybe they have their reasons.
In any case I'd appreciate if you can take a look and see if it solves the problem

### CODE REVIEW

**Comment by ittaiz** [comment]
also, are you using latest gazelle?
https://github.com/bazelbuild/rules_go/issues/1347
cc @barlevalon

**Comment by AlexShemeshWix** [comment]
No i dont use latest gazelle. I use one from releases 0.10.0. But i dont think it matters much.
Yes all the files are generated buy gazelle

**Comment by ittaiz** [comment]
Can you try the latest gazelle? In the issue I referenced the maintainer
says they recently fixed a bug in gazelle

**Comment by AlexShemeshWix** [comment]
last version seems to fix it.

**Pull request closed without merging**
